//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chute_and_Ladders_with_Arithmetic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chute_and_Ladders_with_Arithmetic.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Answer!.
        /// </summary>
        internal static string Correct_Answer {
            get {
                return ResourceManager.GetString("Correct_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chute And Ladders.
        /// </summary>
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn Arithmetic with me.
        /// </summary>
        internal static string GameTitleExtended {
            get {
                return ResourceManager.GetString("GameTitleExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighScore.
        /// </summary>
        internal static string HighScore {
            get {
                return ResourceManager.GetString("HighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5 For Every Move.
        /// </summary>
        internal static string MovePoints {
            get {
                return ResourceManager.GetString("MovePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Saver Question.
        /// </summary>
        internal static string QuestionWindowTitle {
            get {
                return ResourceManager.GetString("QuestionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string ResultWindowTitle {
            get {
                return ResourceManager.GetString("ResultWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        internal static string Roll {
            get {
                return ResourceManager.GetString("Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Won!.
        /// </summary>
        internal static string Win_Message {
            get {
                return ResourceManager.GetString("Win_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And your total Score is.
        /// </summary>
        internal static string Win_Message_Score {
            get {
                return ResourceManager.GetString("Win_Message_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner!.
        /// </summary>
        internal static string WinMessageTite {
            get {
                return ResourceManager.GetString("WinMessageTite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Answer!.
        /// </summary>
        internal static string Wrong_Answer {
            get {
                return ResourceManager.GetString("Wrong_Answer", resourceCulture);
            }
        }
    }
}
